/*
Program is used to calculate the average grade from 4 assignments
Assuming all projects are weighted evenly.
Made by Tarkan Dahi on Febuary 18, 2020
 */

/**
 *
 * @author TaDah5199
 */
public class NewFrm extends javax.swing.JFrame {

    /**
     * Creates new form NewFrm
     */
    public NewFrm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Grade1lbl = new javax.swing.JLabel();
        Grade2lbl = new javax.swing.JLabel();
        Grade3lbl = new javax.swing.JLabel();
        Grade4lbl = new javax.swing.JLabel();
        Grade1Txt = new javax.swing.JTextField();
        Grade2Txt = new javax.swing.JTextField();
        Grade3Txt = new javax.swing.JTextField();
        Grade4Txt = new javax.swing.JTextField();
        AverageBtn = new javax.swing.JButton();
        Averagelbl = new javax.swing.JLabel();
        titleLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Grade1lbl.setText("Grade 1:");

        Grade2lbl.setText("Grade 2");

        Grade3lbl.setText("Grade 3");

        Grade4lbl.setText("Grade 4");

        Grade2Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Grade2TxtActionPerformed(evt);
            }
        });

        AverageBtn.setText("Find Your Average");
        AverageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AverageBtnActionPerformed(evt);
            }
        });

        Averagelbl.setText("Your Average");

        titleLbl.setFont(new java.awt.Font("Ti92Pluspc", 0, 11)); // NOI18N
        titleLbl.setText("Average Grade Calculator");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(AverageBtn)
                .addGap(0, 150, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 104, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Grade1lbl)
                            .addComponent(Grade2lbl, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Grade3lbl, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Grade4lbl, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Grade4Txt, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(Grade3Txt)
                            .addComponent(Grade2Txt)
                            .addComponent(Grade1Txt))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Averagelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLbl)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Grade1lbl)
                    .addComponent(Grade1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Grade2lbl)
                    .addComponent(Grade2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Grade3lbl)
                    .addComponent(Grade3Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Grade4lbl)
                    .addComponent(Grade4Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AverageBtn)
                .addGap(18, 18, 18)
                .addComponent(Averagelbl)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Grade2TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Grade2TxtActionPerformed
       
       
    }//GEN-LAST:event_Grade2TxtActionPerformed

    private void AverageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AverageBtnActionPerformed
       // Variable Declaration area
       double grade1;
       double grade2;
       double grade3;
       double grade4;
       
       double averageMark;
       double averageRoundOff;
       
       // Area for inputing of grades
       grade1 = Integer.parseInt(Grade1Txt.getText());
       grade2 = Integer.parseInt(Grade2Txt.getText());
       grade3 = Integer.parseInt(Grade3Txt.getText());
       grade4 = Integer.parseInt(Grade4Txt.getText());
       
       // Calculation area + output to a label
       averageMark = (grade1 + grade2 + grade3 + grade4)/4;
       
       averageRoundOff = Math.round(averageMark* 10.0) / 10.0;
       
       Averagelbl.setText("Your average is: " + averageRoundOff + "%");
       
    }//GEN-LAST:event_AverageBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AverageBtn;
    private javax.swing.JLabel Averagelbl;
    private javax.swing.JTextField Grade1Txt;
    private javax.swing.JLabel Grade1lbl;
    private javax.swing.JTextField Grade2Txt;
    private javax.swing.JLabel Grade2lbl;
    private javax.swing.JTextField Grade3Txt;
    private javax.swing.JLabel Grade3lbl;
    private javax.swing.JTextField Grade4Txt;
    private javax.swing.JLabel Grade4lbl;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
